spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
      host: mongo-crypto-db
      port: 27017

jwt:
  signing-key: ${JWT_SIGNING_KEY}

server:
  port: 8081