spring:
  application:
    name: crypto-balance-tracker-login
  profiles:
    active: ${ENV_PROFILE:local}
    group:
      default: local

server:
  port: 8081

jwt:
  signing-key: ${JWT_SIGNING_KEY}

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([ %thread ]) %green(%logger) - %boldMagenta(%msg%n)"