spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
      host: mongo-crypto-db
      port: 27017

jwt:
  signing-key: ${JWT_SIGNING_KEY}

server:
  port: 8081

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta([ %thread ]) %green(%logger) - %boldMagenta(%msg%n)"